name: Deploy to Firebase Hosting
"on":
  push:
    paths:
      - "dropf-web/**"
    branches:
      - "main"
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies and Build
        working-directory: dropf-web
        run: |
          npm install
          npm run build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_DROPF_COM }}"
          entryPoint: "./dropf-web"
          channelId: live
          projectId: dropf-com
